# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bab7727713ba6735aa1f1a264f01862b2edba304d413851dd43a256764d0699f267a4f47bb00bd364b306aaa8aed2a0d29921505376b88b79d7ae883eda607e

test:
  secret_key_base: d02fd153a7bf9e6c47d47c17aff7782d66dac859e33930ae9c1ddb3aff3344e4d9462c0a5882551a85dbc5c950bc5df59a3f594c64fd8dee3d1b200090840e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
